admin/src/web/controllers/billing.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from src.core.auth import find_user_by_email
from src.core.persons import get_active_employees
from src.core.payments import create_billing
from src.core.database import db
from src.core.payments.models.billing import Billing
from src.core.persons.models.person import Employee, JyA, Person
from src.core.payments.forms import BillingForm
from src.core.auth.auth import inject_user_permissions, permission_required
from datetime import datetime

bp = Blueprint('billing', __name__, url_prefix='/cobros')


def get_person_name_and_last_name(person_id):
    person = Person.query.filter_by(id=person_id).first()
    if person:
        return person.name + ' ' + person.last_name
    return None, None


@bp.route('/', methods=['GET', 'POST'])
@permission_required('billing_index')
@inject_user_permissions
def list_billings():
    """
        Esta funcion se encarga de listar los cobros realizados
        aplicando filtros de busqueda y realizando la paginacion.

    """

    order = request.args.get('order', 'asc')
    q = request.args.get('q', None)
    start_date_str = request.args.get('start_date', None)
    end_date_str = request.args.get('end_date', None)
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 25, type=int)
    payment_method = request.args.get('payment_method', None)

    if order == 'desc':
        billings_query = Billing.query.order_by(Billing.payment_date.desc())
    else:
        billings_query = Billing.query.order_by(Billing.payment_date.asc())

    if start_date_str:
        start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
        billings_query = billings_query.filter(
            Billing.payment_date >= start_date)

    if end_date_str:
        end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
        billings_query = billings_query.filter(
            Billing.payment_date <= end_date)

    billings_pagination = billings_query.paginate(
        page=page, per_page=per_page, error_out=False)
    billings = billings_pagination.items

    pos = 1
    for billing in billings:
        billing.employee_name = get_person_name_and_last_name(
            billing.employee_id)
        billing.jya_name = get_person_name_and_last_name(billing.jya_id)
        billing.pos = pos
        pos += 1

    if q:
        billings = [billing for billing in billings if q.lower()
                    in billing.employee_name.lower()]

    if payment_method:
        billings = [billing for billing in billings if payment_method.lower(
        ) in billing.payment_method.lower()]

    return render_template('billing/billing_list.html', billings=billings, order=order, q=q, pagination=billings_pagination, payment_method=payment_method, start_date=start_date_str, end_date=end_date_str, form=BillingForm())


@bp.route('/crear', methods=['GET', 'POST'])
@permission_required('billing_new')
@inject_user_permissions
def new_billing():
    """
        Esta funcion se encarga de crear un nuevo cobro.
    """

    form = BillingForm()
    jya_list = JyA.query.all()
    employee_list = get_active_employees()

    employee_actual = find_user_by_email(session.get('user'))

    if employee_actual.system_admin:
        employee_actual = None
    elif employee_actual in employee_list:
        employee_list = employee_list.remove(employee_actual)

    if form.validate_on_submit():
        create_billing(
            employee_id=form.employee_id.data,
            jya_id=form.jya_id.data,
            amount=form.amount.data,
            payment_method=form.payment_method.data,
            observation=form.observation.data
        )
        flash('Billing created successfully!', 'success')
        return redirect(url_for('billing.list_billings'))
    return render_template('billing/billing_new.html', form=form, jya_list=jya_list, employee_list=employee_list, employee_actual=employee_actual)


@bp.route('/cobro/<int:billing_id>', methods=['GET', 'POST'])
@permission_required('billing_show')
@inject_user_permissions
def show_billing(billing_id):
    """
        Esta funcion se encarga de mostrar un cobro en especifico asociado a un id.
    """

    billing = Billing.query.get(billing_id)
    billing.employee_name = get_person_name_and_last_name(billing.employee_id)
    billing.jya_name = get_person_name_and_last_name(billing.jya_id)
    return render_template('billing/billing_show.html', billing=billing)


@bp.route('/cobro/editar/<int:billing_id>', methods=['GET', 'POST'])
@permission_required('billing_edit')
@inject_user_permissions
def edit_billing(billing_id):
    """
        Esta funcion se encarga de editar un cobro en especifico asociado a un id.
    """

    billing = Billing.query.get(billing_id)
    form = BillingForm(obj=billing)
    jya_list = JyA.query.all()
    employee_list = Employee.query.all()

    if form.validate_on_submit():
        billing.employee_id = form.employee_id.data
        billing.jya_id = form.jya_id.data
        billing.amount = form.amount.data
        billing.payment_method = form.payment_method.data
        billing.observation = form.observation.data
        billing.payment_date = form.payment_date.data
        db.session.commit()
        flash('Billing updated successfully!', 'success')
        return redirect(url_for('billing.show_billing', billing_id=billing.id))
    return render_template('billing/billing_edit.html', form=form, jya_list=jya_list, employee_list=employee_list, billing=billing)


@bp.route('/eliminar/<int:billing_id>', methods=['POST'])
@permission_required('billing_delete')
@inject_user_permissions
def delete_billing(billing_id):
    """
    Esta funcion se encarga de eliminar un cobro en especifico asociado a un id.
    """

    billing = Billing.query.get(billing_id)
    if billing:
        db.session.delete(billing)
        db.session.commit()
        flash('Billing deleted successfully!', 'success')
    else:
        flash('Billing not found!', 'danger')
    return redirect(url_for('billing.list_billings'))

admin/src/web/controllers/team.py
from datetime import timedelta
from os import fstat
from flask import Blueprint, current_app as app, render_template, redirect, request, url_for, flash
from src.core.auth.models.user import User
from src.core.persons import create_employee_file, delete_employee_file_by_id, find_address_by_id, find_employee_by_id, find_employee_file_by_id, find_employee_file_by_title, get_emergency_contact_by_id, get_employee_user_by_id, get_files_by_employee_id, get_healthcare_plan_by_id, updated_employee_file
from src.core.auth.auth import inject_user_permissions, permission_required
from src.core.persons.models.person import Employee, Person
from src.core.persons.models.address import Address
from src.core.persons.models.healthcare_plan import HealthcarePlan
from src.core.persons.models.emergency_contact import EmergencyContact
from src.core.persons.forms import EmployeeFileForm, EmployeeForm
from src.core.database import db

bp = Blueprint('team', __name__, url_prefix='/empleados')


@bp.route('/')
@permission_required('team_index')
@inject_user_permissions
def list_team():
    """Redirige a la vista de listado de empleados, con los parámetros de orden, búsqueda, paginación y filtro aplicados.

    Returns:
        render_template: Renderiza la vista de listado de empleados con los parámetros de orden, búsqueda, paginación y filtro aplicados.
        employees: Lista de empleados que cumplen con los parámetros de orden, búsqueda, paginación y filtro aplicados.
        order: Parámetro de orden seleccionado.
        q: Parámetro de búsqueda seleccionado.
        pagination: Paginación de los empleados.
        job_position: Filtro de posición laboral seleccionado.
        form: Formulario de empleado.
    """
    order = request.args.get('order', 'last_name_asc')
    q = request.args.get('q', None)
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 25, type=int)
    job_position = request.args.get('job_position', None)

    # Ordeno según el parámetro seleccionado
    if order == 'last_name_asc':
        employees = Employee.query.order_by(Employee.last_name.asc())
    elif order == 'last_name_desc':
        employees = Employee.query.order_by(Employee.last_name.desc())
    elif order == 'name_asc':
        employees = Employee.query.order_by(Employee.name.asc())
    elif order == 'name_desc':
        employees = Employee.query.order_by(Employee.name.desc())
    elif order == 'date_asc':
        employees = Employee.query.order_by(Employee.start_date.asc())
    else:
        employees = Employee.query.order_by(Employee.start_date.desc())

    # Elimino del query aquellos empleados logicamente
    employees = employees.filter(Employee.email.notlike('*%'))

    # Aplico paginación al query
    employees_pagination = employees.paginate(
        page=page, per_page=per_page, error_out=False)

    # Me quedo con los objetos resultantes de la paginación
    employees = employees_pagination.items

    # Si se realizo una búsqueda, busco si "q" está presente en alguno de los campos
    if q:
        employees = [employee for employee in employees if q.lower() in employee.name.lower() or q.lower(
        ) in employee.last_name.lower() or q.lower() in employee.email.lower() or q in employee.DNI]

    # Si se aplico un filtro según la posición, me quedo solo con los que apliquen
    if job_position:
        employees = [
            employee for employee in employees if job_position == employee.job_position]

    return render_template('team/team_list.html', employees=employees, order=order, q=q, pagination=employees_pagination, job_position=job_position, form=EmployeeForm())


@bp.route('/crear', methods=['GET', 'POST'])
@permission_required('team_new')
@inject_user_permissions
def new_employee():
    """Redirige a la vista de creación de empleado, con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.

    Returns:
        render_template: Renderiza la vista de creación de empleado con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.
        professions: Lista de profesiones.
        form: Formulario de empleado.
        redirect: Redirige a la vista de listado de empleados si el formulario es válido.
    """
    form = EmployeeForm()
    form.address_id.choices = [(address.id, address.string())
                               for address in Address.query.all()]
    form.emergency_contact.choices = [(emergency_contact.id, emergency_contact.name,
                                       emergency_contact.phone_number) for emergency_contact in EmergencyContact.query.all()]
    form.user_id.choices = [(user.id, user.email) for user in User.query.all()]
    professions = ["Psicólogo", "Psicomotricista", "Médico", "Kinesiólogo", "Terapista Ocupacional",
                   "Psicopedagogo", "Docente", "Profesor", "Fonoaudiólogo", "Veterinario", "Otro"]

    if form.validate_on_submit():
        if form.address_id.data:
            address = Address.query.get(form.address_id.data)
        else:
            address = Address(
                street=form.new_address.street.data,
                number=form.new_address.number.data,
                department=form.new_address.department.data,
                locality=form.new_address.locality.data,
                province=form.new_address.province.data,
                phone_number=form.new_address.phone_number.data
            )
            db.session.add(address)
            db.session.commit()

        healthcare_plan = HealthcarePlan(
            social_security=form.healthcare_plan.social_security.data,
            affiliate_number=form.healthcare_plan.affiliate_number.data,
            has_guardianship=form.healthcare_plan.has_guardianship.data,
            observation=form.healthcare_plan.observation.data
        )
        db.session.add(healthcare_plan)
        db.session.commit()

        if form.emergency_contact.data:
            emergency_contact = EmergencyContact.query.get(
                form.emergency_contact.data)
        else:
            emergency_contact = EmergencyContact(
                name=form.new_emergency_contact.name.data,
                phone_number=form.new_emergency_contact.phone_number.data
            )
            db.session.add(emergency_contact)
            db.session.commit()

        employee = Employee(
            name=form.name.data,
            last_name=form.last_name.data,
            DNI=form.dni.data,
            phone_number=form.phone_number.data,
            address_id=address.id,
            profession=form.profession.data,
            job_position=form.job_position.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            emergency_contact_id_employee=emergency_contact.id,
            condition=form.condition.data,
            active=True,
            healthcare_plan_id_employee=healthcare_plan.id,
            email=form.email.data,
            birth_date=form.birth_date.data,
            user_id=form.user_id.data
        )
        db.session.add(employee)
        db.session.commit()
        flash('Employee created successfully!', 'success')
        return redirect(url_for('team.list_team'))

    return render_template('team/team_new.html', form=form, professions=professions)


@bp.route('/empleado/<int:id>')
@permission_required('team_show')
@inject_user_permissions
def show_employee(id):
    """Redirige a la vista de detalle de empleado, con los archivos asociados al empleado.

    Args:
        id (int): ID del empleado.

    Returns:
        render_template: Renderiza la vista de detalle de empleado con los archivos asociados al empleado.
        context: Contexto con los archivos asociados al empleado.
    """

    app.logger.info("Call to index function")

    employee = find_employee_by_id(id)

    # Quita el asterisco si el empleado fue eliminado logicamente
    if employee.email.startswith('*'):
        employee.email = employee.email[1:]

    employee_address = find_address_by_id(employee.address_id).string()
    employee_healthcare_plan = get_healthcare_plan_by_id(
        employee.healthcare_plan_id_employee)
    employee_emergency_contact = get_emergency_contact_by_id(
        employee.emergency_contact_id_employee)
    employee_user = get_employee_user_by_id(employee.user_id)
    files = get_files_by_employee_id(employee.id)
    employee_json = employee.to_dict(employee_address, employee_healthcare_plan,
                                     employee_emergency_contact, employee_user.email if employee_user else None)
    employee_json['active'] = 'Activo' if employee.active else 'Inactivo'

    files_json = []
    if files:
        for file in files:
            files_json.append(file.to_dict())

    if not employee_json['user']:
        employee_json['user'] = 'No asignado'

    context = {
        'files': files_json,
        'user': employee_json,
        'id': id,
    }

    app.logger.info("End of call to index function")

    return render_template('team/team_show.html', context=context)


@bp.route('/empleado/editar/<int:id>', methods=['GET', 'POST'])
@permission_required('team_update')
@inject_user_permissions
def edit_employee(id):
    """Redirige a la vista de edición de empleado, con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.

    Args:
        id (int): ID del empleado.

    Returns:
        render_template: Renderiza la vista de edición de empleado con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.
        professions: Lista de profesiones.
        form: Formulario de empleado.
        redirect: Redirige a la vista de listado de empleados si el formulario es válido.
    """

    employee = Employee.query.get(id)
    employee.healthcare_plan = HealthcarePlan.query.get(
        employee.healthcare_plan_id_employee)

admin/src/web/templates/billing/billing_edit.html
{% extends "layout.html" %}
{% block title %}Editar cobro{% endblock %}
{% block head %}
    {{ super() }}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/payment_and_billing/edit.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
{% endblock %}
{% block content %}
<form method="POST" action="{{ url_for('billing.edit_billing', billing_id=billing.id) }}">
    {{ form.csrf_token }}

    <div class="div-titulo">
        <h1 class="label">Editar cobro</h1>
        <hr class="linea-titulo">
    </div>

    <label class="label" for="jya_id">J&A</label>
    <div class="control">
        <select name="jya_id" id="jya_id">
            <option value=""></option>
            {% for jya in jya_list %}
            <option value="{{ jya.id }}" {% if jya.id == billing.jya_id %}selected{% endif %}>{{ jya.name }} {{ jya.last_name }}</option>
            {% endfor %}
        </select>
        {% if form.jya_id.errors %}
            <div class="alert alert-danger">
                {% for error in form.jya_id.errors %}
                    <span style="color: red">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <hr style="margin-top: 0;">

    <label class="label" for="payment_date">Fecha de pago</label>
    <input class="input" type="date" name="payment_date" id="payment_date" value="{{ billing.payment_date.strftime('%Y-%m-%d') }}">
    {% if form.payment_date.errors %}
            <div class="alert alert-danger">
                {% for error in form.payment_date.errors %}
                    <span style="color: red">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    <hr>

    <label class="label" for="payment_method">Metodo de pago</label>
    <div class="control">
        <select name="payment_method" id="payment_method">
            <option value=""></option>
            <option value="Efectivo" {% if billing.payment_method == 'Efectivo' %}selected{% endif %}>Efectivo</option>
            <option value="Tarjeta de credito" {% if billing.payment_method == 'Tarjeta de credito' %}selected{% endif %}>Tarjeta de crédito</option>
            <option value="Tarjeta de debito" {% if billing.payment_method == 'Tarjeta de debito' %}selected{% endif %}>Tarjeta de débito</option>
            <option value="Otro" {% if billing.payment_method == 'Otro' %}selected{% endif %}>Otro</option>
        </select>
    </div>
    {% if form.payment_method.errors %}
            <div class="alert alert-danger">
                {% for error in form.payment_method.errors %}
                    <span style="color: red">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    <hr style="margin-top: 0;">

    <label class="label" for="amount">Monto</label>
    <input class="input" name="amount" type="number" step="0.01" min="0" value="{{ billing.amount }}">
    {% if form.amount.errors %}
            <div class="alert alert-danger">
                {% for error in form.amount.errors %}
                    <span style="color: red">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    <hr style="margin-top: 0;">

    <label class="label" for="employee_id">Empleado</label>
    <div class="control">
        <select name="employee_id" id="employee_id">
            <option value=""></option>
            {% for employee in employee_list %}
            <option value="{{ employee.id }}" {% if employee.id == billing.employee_id %}selected{% endif %}>{{ employee.name }} {{ employee.last_name }}</option>
            {% endfor %}
        </select>
        {% if form.employee_id.errors %}
            <div class="alert alert-danger">
                {% for error in form.employee_id.errors %}
                    <span style="color: red">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <hr style="margin-top: 0;">

    <label class="label" for="observation">Observaciones:</label>
    <textarea class="textarea" type="text" name="observation" id="observation">{{ billing.observation }}</textarea>
    {% if form.observation.errors %}
            <div class="alert alert-danger">
                {% for error in form.observation.errors %}
                    <span style="color: red" >{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    <hr>

    <div class="buttons">
        <a class="a-button" href="{{ url_for('billing.show_billing', billing_id = billing.id) }}" style="color: white;"><button type="button">Cancelar</button></a>
        <button type="submit">Actualizar</button>
    </div>
        
</form>

<script>
    $(document).ready(function () {
        //Script para el select de J&A
        $('select').selectize({
            sortField: 'text'
        });
    });
    var today = new Date().toISOString().split('T')[0];
    document.getElementById('payment_date').setAttribute('max', today);
</script>

{% endblock %}

admin/src/web/templates/billing/billing_list.html
{% extends "layout.html" %}
{% block title %}Cobros{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/payment_and_billing/list.css') }}">
{% endblock %}

{% block content %}



<div class="container">
    <div class="header-container">
        <h1 class="is-size-2-mobile is-size-2-tablet is-size-2-desktop">Lista de Cobros</h1>
        <a href="{{ url_for('billing.new_billing') }}" class="button is-white is-size-6">Agregar cobro</a>
    </div>

    <div class="search-container">
            <form class="form-container" method="get" action="{{ url_for('billing.list_billings') }}">
                <div class="columns is-multiline">
                    <div class="column is-narrow">
                        <input class="input" type="text" name="q" placeholder="Buscar por nombre" value="{{ request.args.get('q', '') }}">
                    </div>
                    <div class="column is-narrow">
                        <div class="select">
                            <select name="order" id="order" onchange="this.form.submit()">
                                <option value="asc" {% if order == 'asc' %}selected{% endif %}>Orden Ascendente</option>
                                <option value="desc" {% if order == 'desc' %}selected{% endif %}>Orden Descendente</option>
                            </select>
                        </div>
                    </div>
                    <div class="column is-narrow">
                        <div class="select">
                            <select name="payment_method" id="payment_method" onchange="this.form.submit()">
                                <option value="">Metodo de pago</option>
                                <option value="efectivo" {% if payment_method == 'efectivo' %}selected{% endif %}>Efectivo</option>
                                <option value="credito" {% if payment_method == 'credito' %}selected{% endif %}>Tarjeta de crédito</option>
                                <option value="debito" {% if payment_method == 'debito' %}selected{% endif %}>Tarjeta de débito</option>
                                <option value="otro" {% if payment_method == 'otro' %}selected{% endif %}>Otro</option>
                            </select>
                        </div>
                    </div>
                    <div class="column is-narrow">
                        <input class="input" type="date" id="start_date" name="start_date" value="{{ request.args.get('start_date', '') }}">
                    </div>
                    <div class="column is-narrow">
                        <input class="input" type="date" id="end_date" name="end_date" value="{{ request.args.get('end_date', '') }}">
                    </div>
                    <div class="column is-narrow">
                        <button type="submit" class="button search-button">Buscar</button>
                    </div>
                    <div class="column is-narrow">
                        <a class="button restore-button" href="{{ url_for('billing.list_billings', page=page) }}">Restablecer</a>
                    </div>
                </div>
            </form>
    </div>

    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Empleado</th>
                    <th>JYA</th>
                    <th>Monto</th>
                    <th>Dia</th>
                    <th>Metodo de pago</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% if billings %}
                    {% for billing in billings %}
                    <tr>
                        <td>{{ billing.pos }}</td>
                        <td><a href="{{ url_for('team.show_employee', id=billing.employee_id) }}">{{ billing.employee_name }}</a></td>
                        <td><a href="{{ url_for('horsemen_and_amazons.list_info_by_jya', user_id=billing.jya_id) }}">{{ billing.jya_name }}</a></td>
                        <td>{{ billing.amount }}</td>
                        <td>{{ billing.payment_date.strftime('%d-%m-%Y') }}</td>
                        <td>{{ billing.payment_method }}</td>
                        <td>
                            <a href="{{ url_for('billing.show_billing', billing_id=billing.id) }}" class="button is-small is-white"><i class="fas fa-eye" title="Ver"></i></a>
                            <a href="{{ url_for('billing.edit_billing', billing_id=billing.id) }}" class="button is-small is-white"><i class="fas fa-edit" title="Editar"></i></a>
                            <a class="button is-small is-white delete-button" data-billing-id="{{ billing.id }}" data-billing-pos="{{ billing.pos }}"><i class="fas fa-trash" title="Eliminar"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5">No hay cobros</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous" {% if not pagination.has_prev %}disabled{% else %}href="{{ url_for('billing.list_billings', page=pagination.prev_num,  order=order, q=q) }}"{% endif %}>Previous</a>
        <a class="pagination-next" {% if not pagination.has_next %}disabled{% else %}href="{{ url_for('billing.list_billings', page=pagination.next_num,  order=order, q=q) }}"{% endif %}>Next page</a>
    </nav>
</div>

<div id="deleteModal" class="modal">
    <div class="modal-content">
        <h3>¿Estás seguro de que deseas eliminar el cobro de ID:<span id="billingPosToDelete"></span>?</h3>
        <div class="modal-actions">
            <button id="cancelButton" class="button">Cancelar</button>
            <button id="confirmButton" class="button is-danger">Eliminar</button>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const deleteButtons = document.querySelectorAll('.delete-button');
        const deleteModal = document.getElementById('deleteModal');
        const cancelButton = document.getElementById('cancelButton');
        const confirmButton = document.getElementById('confirmButton');
        const billingPosToDeleteSpan = document.getElementById('billingPosToDelete');
        let billingIdToDelete = null;

        deleteButtons.forEach(button => {
            button.addEventListener('click', function () {
                billingIdToDelete = this.dataset.billingId;
                billingPosToDelete = this.dataset.billingPos;
                billingPosToDeleteSpan.textContent = billingPosToDelete;
                deleteModal.style.display = 'block';
            });
        });

        cancelButton.addEventListener('click', function () {
            deleteModal.style.display = 'none';
            billingIdToDelete = null;
        });

        confirmButton.addEventListener('click', function () {
            if (billingIdToDelete) {
                fetch(`/cobros/eliminar/${billingIdToDelete}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ form.csrf_token._value() }}'
                    }
                }).then(response => {
                    if (response.ok) {
                        window.location.reload();
                    } else {
                        alert('Error al eliminar el cobro');
                    }
                });
            }
        });

        window.onclick = function (event) {
            if (event.target == deleteModal) {
                deleteModal.style.display = 'none';
            }
        }
    });
    var today = new Date().toISOString().split('T')[0];
    document.getElementById('start_date').setAttribute('max', today);
    document.getElementById('end_date').setAttribute('max', today);
</script>

{% endblock %}

admin/src/web/templates/billing/billing_show.html
{% extends "layout.html" %}
{% block title %}Cobro{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/payment_and_billing/show.css') }}">
{% endblock %}


{% block content %}

<form action="">
    <div class="div-titulo">
        <h1 class="label">Cobro</h1>
        <hr class="linea-titulo">
    </div>

    <label class="label" for="jya_id">J&A</label>
    <div class="control">
        <input disabled type="text" value="{{ billing.jya_name }}">
    </div>
    <hr style="margin-top: 0;">

    <label class="label" for="payment_date">Fecha de pago</label>
    <input disabled type="date" name="payment_date" id="payment_date" value="{{ billing.payment_date.strftime('%Y-%m-%d') }}">
    <hr>

    <label class="label" for="payment_method">Metodo de pago</label>
    <div class="control">
        <input disabled type="text" value="{{ billing.payment_method }}">
    </div>
    <hr style="margin-top: 0;">

    <label class="label" for="amount">Monto</label>
    <input disabled name="amount" type="number" step="0.01" value="{{ billing.amount }}">
    <hr style="margin-top: 0;">

    <label class="label" for="employee_id">Empleado</label>
    <div class="control">
        <input disabled type="text" value="{{ billing.employee_name }}">
    </div>
    <hr style="margin-top: 0;">

    <label class="label" for="observation">Observaciones:</label>
    <input disabled type="text" name="observation" id="observation" value="{{ billing.observation }}">
    <hr>

    <div class="buttons">
        <a class="a-button" href="{{ url_for('billing.list_billings') }}"><button type="button">Listado de cobros</button></a>
        <a class="a-button" href="{{ url_for('billing.edit_billing', billing_id = billing.id) }} "><button type="button">Editar</button></a>
    </div>
</form>

{% endblock %}