admin/src/web/controllers/horsemen_and_amazons.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from src.core.persons import (find_address_by_id, find_jya_by_id, delete_jya_by_id, get_files_by_horseman_id, delete_file_by_id, 
                              create_JyA, create_file, create_address, create_emergency_contact, create_healthcare_plan, updated_jya, find_file_by_title, find_file_by_id, updated_file, 
                              get_emergency_contacts, get_address,get_emergency_contact_by_id, get_healthcare_plan_by_id, updated_healthcare_plan, update_address, update_emergency_contact)
from src.core.institutions import get_school_by_id, create_school, update_school
from src.core.persons.forms import registryFileForm, registryHorsemanForm
from src.core.auth.auth import inject_user_permissions, permission_required
from web.handlers.storage import get_bucket_and_server_minio
from flask import current_app as app
from datetime import timedelta
from src.core.persons.models.file import File
from src.core.persons.models.person import JyA
from web.validations import validate_horseman_form, validate_unique_fields_horseman
from sqlalchemy import desc
import io
from os import fstat


bp = Blueprint("horsemen_and_amazons", __name__, url_prefix="/users-jya")

def showHorsemen(request):
    
    """
        Muestra una lista paginada de jinetes y amazonas (JyA) con opciones de filtrado y ordenación.

        Esta función permite filtrar y ordenar los registros de jinetes y amazonas según varios criterios 
        como nombre, apellido, DNI y profesionales a cargo. Además, la lista se presenta de forma paginada.

        Parámetros:
        request (Request): El objeto de la solicitud HTTP que contiene los parámetros de la consulta. 
            - order_option (str): Opción de ordenación, como 'name_asc', 'name_desc', 'last_name_asc', o 'last_name_desc'.
            - page (int): El número de página para la paginación (predeterminado: 1).
            - name (str): Filtro por nombre del jinete/amazona (opcional).
            - last_name (str): Filtro por apellido del jinete/amazona (opcional).
            - dni (str): Filtro por DNI del jinete/amazona (opcional).
            - professionals (str): Filtro por nombre de los profesionales a cargo (opcional).

        Retorna:
        tuple: Una tupla que contiene:
            - horsemen (Pagination): Un objeto de paginación con los registros filtrados y ordenados de jinetes y amazonas.
            - page (int): El número de página actual.
            - order_by (str): La opción de ordenación seleccionada.
            - name (str): El filtro aplicado por nombre.
            - last_name (str): El filtro aplicado por apellido.
            - dni (str): El filtro aplicado por DNI.
            - attending_professionals (str): El filtro aplicado por profesionales a cargo.

    """
    # Determine the order option
    if request.method == 'POST':
        order_by = request.args.get('order_option', 'name_asc', type=str)
    else:
        order_by = request.args.get('order_option', 'name_asc', type=str)

    app.logger.info("Call to showHorsemen function with order_option: %s", order_by)
    
    # Map order options to actual column sorting
    order_mapping = {
        'name_asc': JyA.name,
        'name_desc': desc(JyA.name),
        'last_name_asc': JyA.last_name,
        'last_name_desc': desc(JyA.last_name),
    }

    order_criteria = order_mapping.get(order_by, File.title)

    # Pagination
    page = request.args.get('page', 1, type=int)
    
    is_filter_active = False
    
    # Filtering options
    name = request.args.get('name', '', type=str)
    last_name = request.args.get('last_name', '', type=str)
    dni = request.args.get('dni', '', type=str)
    attending_professionals = request.args.get('professionals', '', type=str)

    if name or last_name or dni or attending_professionals:
        is_filter_active = True

    app.logger.info("Name: %s,  Last Name: %s, DNI: %s, Profesionales: %s", name, last_name, dni, attending_professionals)

    # Build the query
    query = JyA.query
    
    if name:
        query = query.filter(JyA.name.ilike(f'%{name}%'))
    if last_name:
        query = query.filter(JyA.last_name.ilike(f'%{last_name}%'))
    if dni:
        query = query.filter(JyA.DNI.ilike(f'%{dni}%'))
    if attending_professionals:
        query = query.filter(JyA.attending_professionals.ilike(f'%{attending_professionals}%'))

    
    
    # Apply ordering and pagination
    horsemen = query.order_by(order_criteria).paginate(page=page, per_page=2)

    app.logger.info("End of call to showHorsemen function")

    return horsemen, page, order_criteria , name, last_name, dni, attending_professionals, is_filter_active

def obtenerChoices(form):

    """ Esta función recibe el formulario de jinetes y amazonas y devuelve las instituciones, los contactos de emergencia, y las direcciones, 
        utilizadas como opciones de los distintos campos del formulario.


        Parámetros:
            - form (FlaskForm): Formulario de jinetes y amazonas.
        
    """

    emergency_contacts = get_emergency_contacts()

    addresses = get_address()

    # Asignar el id como value y la representación amigable como label
    form.address_id.choices = [(address.id, address.string()) for address in addresses]
    form.emergency_contact_id_jya.choices = [(emergency_contact.id, emergency_contact.name, emergency_contact.phone_number) for emergency_contact in emergency_contacts]

@bp.get("/")
@permission_required('jya_index')
@inject_user_permissions
def list_jya_users():

    """ 
        Muestra la vista del listado de los jinetes y amazonas registrados en el sistema    
    """

    horsemen, page, order_criteria, name, last_name, dni, attending_professionals, is_filter_active = showHorsemen(request)

    return render_template("horsemen_and_amazons/jya_users_list.html", users = horsemen, page=page, order_by=order_criteria, name=name, last_name=last_name, dni=dni, professionals=attending_professionals, is_filter_active=is_filter_active)

def showFiles(request, horseman_id):

    """
         Obtiene una lista paginada de archivos con opciones de filtrado y ordenación.

        Esta función recupera archivos de la base de datos basándose en varios parámetros de consulta opcionales: términos de búsqueda, tipo de documento, 
        orden de clasificación y paginación. Si no se proporcionan parámetros, se ordena de forma predeterminada por título en orden ascendente.

        Parámetros:
            request (flask.Request): El objeto de solicitud de Flask que contiene posibles parámetros de consulta para el filtrado, ordenación y paginación.

        Parámetros de consulta:
            - order_option (str): Define el orden de clasificación de los archivos.
                Valores posibles:
                * 'title_asc' (predeterminado): Ordena por título en orden ascendente.
                * 'title_desc': Ordena por título en orden descendente.
                * 'date_asc': Ordena por fecha de subida en orden ascendente.
                * 'date_desc': Ordena por fecha de subida en orden descendente.
            - search (str): Un término de búsqueda usado para filtrar archivos por título (predeterminado: '').
            - document_type (str): Filtra por tipo de documento específico (predeterminado: '').
            - page (int): El número de página actual para la paginación (predeterminado: 1).

        Retorna:
            tuple: Una tupla que contiene lo siguiente:
                - files (Pagination): Una lista paginada de archivos.
                - page (int): El número de página actual.
                - order_by (str): La opción de orden seleccionada para la clasificación.
                - search (str): El término de búsqueda usado para filtrar.
                - document_type (str): El filtro aplicado por tipo de documento.
    """
    
    order_by = request.args.get('order_option', 'title_asc', type=str)


    app.logger.info("Call to order_by function with order_option: %s", order_by)
    
    # Map order options to actual column sorting
    order_mapping = {
        'title_asc': File.title,
        'title_desc': desc(File.title),
        'date_asc': File.upload_date,
        'date_desc': desc(File.upload_date),
    }

    order_criteria = order_mapping.get(order_by, File.title)

    # Pagination
    page = request.args.get('page', 1, type=int)
    
    is_filter_active = False
    # Filtering options
    search = request.args.get('search', '', type=str)
    document_type = request.args.get('document_type', '', type=str)

    if search or document_type:
        is_filter_active = True

    app.logger.info("Search: %s, Document_Type: %s", search, document_type)

    # Build the query
    query = File.query.filter(File.horsemen_and_amazons_id == horseman_id)
    
    if search:
        query = query.filter(File.title.ilike(f'%{search}%'))
    if document_type and document_type != 'Selecciona un tipo':
        query = query.filter(File.document_type == document_type)
    
    # Apply ordering and pagination
    files = query.order_by(order_criteria).paginate(page=page, per_page=2, error_out=False)

    app.logger.info("Total files found: %d", query.count())
    app.logger.info("Page: %d", page)

    app.logger.info("End of call to order_by function")

    return files, page, order_by, search, document_type, is_filter_active


@bp.get("/<int:user_id>")
@permission_required('jya_show')
@inject_user_permissions
def list_info_by_jya(user_id):

    """
        Esta función retorna la información del jinete o amazona asociado al id pasado por parámetro en la url.

        Parámetros:
            user_id (int): Id del jinete del cual se necesita la información.
    """
    
    app.logger.info("Call to index function")

    jya = find_jya_by_id(user_id)
    jya_address = find_address_by_id(jya.address_id).string()
    jya_json = jya.to_dict(jya_address)
    files_json = []

admin/src/web/templates/error.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ error.title }}</title>

    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/error.css') }}">
    {% endblock %}

</head>
<body>
    <div class="error-container">
        <div class="error-code">{{ error.code }}</div>
        <div class="error-message">{{ error.message }}</div>
        <div class="error-details">{{ error.description }}</div>
        <div class="link-container">
            <a href="{{ url_for('home') }}" class="more-link">Ir al inicio</a>
        </div>
    </div>
</body>
</html>

admin/src/web/templates/home.html
{% extends "layout.html" %}

{% block title %}Pagina de Inicio{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

admin/src/web/templates/layout.html
<!DOCTYPE html>

<html lang="en">
    <head>
        {% block head %}
        <meta charset="UTF-8">
        <meta name="description" content="El Centro de Equitación para Personas con Discapacidad y Carenciadas, CEDICA, es una Asociación Civil sin Fines de Lucro, fundada en 1994 en la ciudad de La Plata, Provincia de Buenos Aires, Argentina. CEDICA trabaja con la finalidad de IGUALAR OPORTUNIDADES en procura de la reinserción familiar, el logro de la escolaridad, la integración laboral y la mejora integral de la calidad de vida de los J&A (“Jinetes” y “Amazonas”) que forman parte de la institución.
        Las actividades que se realizan se denominan Terapias y Actividades asistidas con Caballos –TACAs-, aunque históricamente también fueron conocidas con otros términos como Rehabilitación Ecuestre o Equinoterapia. Se trata de una terapia integral que apunta a la recuperación de la persona en sus dimensiones biológica, psíquica y social. El principal recurso de trabajo es el Caballo, como mediador y facilitador de las intervenciones terapéuticas que cada profesional de la salud o la educación planifica para las diferentes Personas con Discapacidad que asisten a la institución.
        CEDICA cuenta con un Equipo de trabajo integrado por personal ecuestre, técnicos y profesionales: Terapistas Ocupacionales (T.O.), Psicólogos, Psicopedagogos, Psicomotricistas, Profesores de Educación Física y Equitación; Instructores de Volteo; Médico Veterinario, capacitados en TACAs. A ello se suman anualmente una gran cantidad de voluntarios, en su mayoría estudiantes universitarios de la UNLP y la UNQUI; y el plantel se completa con los caballos en actividad y potrillos en etapa de entrenamiento.
        Este Equipo de trabajo se divide en 5 grandes Áreas, a saber: Área Técnica, Área Ecuestre, Área de Voluntariado, Área de Gestión y Administración; y Área de Capacitación. Cada una de ellas, cuenta con sus propios Procesos de Trabajo para cumplir con la tarea y los objetivos institucionales."/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='styles/style.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='styles/flash.css') }}"
        />
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='styles/navbar.css') }}"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
        <link rel="icon" href="/static/logos/favicon.png" type="image/png">
        <meta name="google-site-verification" content="M9BWQjY2pwU9TRpmr96wbXKFlA5zhwZ6xCcPsynmSoA" />
        <title>{% block title %}{% endblock %}</title>
        {% endblock %}
    </head>
    <body>
        <div>
            {% block navbar %} 
            <nav class="navbar is-white" style="background-color: white;" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a href="{{ url_for('home') }}">
                        <img class="navbar-item navbar-logo" src="{{ url_for('static', filename='logos/cedica.png') }}">
                    </a>
        
                  <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarElement">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                  </a>
                </div>
                
                <div id="navbarElement" class="navbar-menu">
                  <div class="navbar-start">
                  {% if 'jya_index' in g.user_permissions or g.user_system_admin %}
                    <a class="navbar-item" href="{{ url_for('horsemen_and_amazons.list_jya_users') }}" >
                      J&A
                    </a>
                    {% endif %}

                    {% if 'horse_index' in g.user_permissions or g.user_system_admin %}
                    <a class="navbar-item" href=" {{ url_for('horses.list_horses') }}">
                      Ecuestre
                    </a>
                    {% endif %}

                    {% if 'team_index' in g.user_permissions or g.user_system_admin %}
                    <a class="navbar-item" href="{{ url_for('team.list_team') }}">
                        Equipo
                    </a>
                    {% endif %}
                    {% if 'billing_index' in g.user_permissions or g.user_system_admin %}
                    <a class="navbar-item" href="{{ url_for('billing.list_billings') }}">
                        Cobros
                    </a>
                    {% endif %}

                    {% if 'payment_index' in g.user_permissions or g.user_system_admin %}
                    <a class="navbar-item" href="{{url_for('payment.list_payments')}}">
                        Pagos
                    </a>
                    {% endif %}

                    {% if g.user_system_admin %}
                    <a class="navbar-item" href=" {{ url_for('users.index') }}">
                        Usuarios
                    </a>
                    {% endif %}

                  </div>
                
                <div class="navbar-end">
                  <div class="navbar-item">
                    {% if is_authenticated(session) %}
                      <div class="navbar-item user-dropdown is-hidden-touch">
                        <i class="fas fa-user-circle user-icon" id="userIcon"></i>
                        <div class="dropdown-content" id="userDropdown">
                          <div class="user-info">
                            <div class="user-alias"> {{ user(session).alias }}</div>
                            <div class="user-email"> {{ user(session).email }} </div>
                          </div>
                          <a class="dropdown-item" href="{{ url_for('users.show_user', id=session["user_id"]) }}">
                            <i class="fas fa-user"></i>
                            <span>Mi Perfil</span>
                          </a>
                          <a class="dropdown-item" href="{{ url_for('login.logout') }}" >
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Cerrar Sesión</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                      <div class="is-hidden-desktop">
                        <a class="navbar-item" href="{{ url_for('users.show_user', id=session["user_id"]) }}">
                          Perfil
                        </a>
                        <a class="navbar-item" href="/configuracion">
                          Configuración
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{{ url_for('login.logout') }}">
                          Cerrar sesión
                        </a>
                      </div>
                      <script>
                          document.addEventListener('DOMContentLoaded', () => {
                              const userIcon = document.getElementById('userIcon');
                              const userDropdown = document.getElementById('userDropdown');
                  
                              userIcon.addEventListener('click', (e) => {
                                  e.stopPropagation();
                                  userDropdown.classList.toggle('show');
                              });
                  
                              document.addEventListener('click', (e) => {
                                  if (!userDropdown.contains(e.target) && !userIcon.contains(e.target)) {
                                      userDropdown.classList.remove('show');
                                  }
                              });
                          });
                      </script>
                      {% else %}
                        <a class="button is-light login-button" style="background-color: var(--primary-color) !important" href=" {{ url_for('login.login') }}">
                          Iniciar Sesión
                        </a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </nav>
            {% endblock %}
        </div>
        <!-- bloque para los mensajes flash -->
      <div class="container">
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      <div class="notification is-{{ category }} is-flex is-allign-items-center">
                        <div class="content-wrapper">
                          <span class="icon">
                              <i class="icon-notification fas 
                                {% if category == 'info' %} fa-info-circle has-text-info 
                                {% elif category == 'success' %} fa-check-square has-text-success
                                {% elif category == 'warning' %} fa-exclamation-triangle has-text-warning
                                {% elif category == 'error' %} fa-ban has-text-danger
                                {% endif %}">
                              </i>
                            </span>
                          <span class="message">{{ message }}</span>
                        </div>
                        <button class="delete"></button>
                      </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
      </div>
        <div id="container">
            {% block content %}
            {% endblock %}
        </div>
        <div>{% block footer %} {% endblock %}</div>
         <!-- Script para ocultar los mensajes flash automáticamente -->
         <script>
          document.addEventListener('DOMContentLoaded', () => {
              // Encuentra todas las notificaciones flash
              const notifications = document.querySelectorAll('.notification');

              console.log(notifications)
              // Establecer el tiempo de desaparición (en milisegundos)
              const timeout = 3000; // 3 segundos

              notifications.forEach(notification => {
                  // Ocultar la notificación después de 3 segundos
                  setTimeout(() => {
                      notification.remove();
                      console.log("Entre en el timeout")
                  }, timeout);
            
                  // Opción para cerrar manualmente
                  const deleteButton = notification.querySelector('.delete');
                  if (deleteButton) {
                      console.log("Entre en el delete")
                      deleteButton.addEventListener('click', () => {
                          notification.remove();
                      });
                  }
              });
          });
      </script>
      <!-- Script para el navbar burger -->
      <script>
        document.addEventListener('DOMContentLoaded', () => {
    
          // Get all "navbar-burger" elements
          const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
    
          // Add a click event on each of them
          $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {
    
              // Get the target from the "data-target" attribute
              const target = el.dataset.target;
              const $target = document.getElementById(target);
    
              // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
              el.classList.toggle('is-active');
              $target.classList.toggle('is-active');
    
            });
          });
    
        });
    </script>
    </body>
</html>