admin/src/web/controllers/horses.py
from flask import Blueprint, request, flash, session, redirect, render_template, url_for
from src.core.auth.auth import inject_user_permissions, permission_required
from src.core.horses.models.horse import Horse
from src.core.database import db
from src.core.horses.forms import create_horse_Form, registryFileForm
from flask import current_app as app
from src.core.horses.__init__ import create_horse, find_horse_by_id, find_file_by_id, delete_file_by_id, create_file, find_file_by_title, updated_file
from sqlalchemy import desc
from src.core.persons import Employee
from src.core.horses.models.horses_file import Horse_file
from datetime import timedelta
import json
import io
from os import fstat

bp = Blueprint('horses', __name__, url_prefix='/horses')


@bp.get("/")
@permission_required('horse_index')
@inject_user_permissions
def list_horses():

    """
    Esta función retorna el listado de los caballos registrados en el sistema, 
    aplicando filtros de búsqueda, ordenación y paginación. 
    Permite filtrar por nombre y tipo de jinete/amazona asignado, y 
    ordenar por nombre, fecha de nacimiento o fecha de entrada de forma ascendente o descendente.


    Returns:
        render_template: Renderiza la plantilla 'ecuestre/horses.html' con los siguientes parámetros:
            - horses (list): Lista de objetos Horse correspondientes a la página actual, filtrados según los criterios aplicados.
            - order (str): El criterio de ordenamiento seleccionado.
            - q (str): Parámetro de búsqueda seleccionado.
            - pagination (Pagination): Objeto de paginación con información de la página actual, total de páginas y registros.
            - type_jya_assigned (str): El tipo de jinete/amazona aplicado como filtro (si corresponde).
            - form (Form): El formulario para crear un nuevo caballo.
    """

    order = request.args.get('order', 'name_asc') #orden default por nombre ascendente 
    q = request.args.get('q', None)
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 2, type=int)
    type_jya = request.args.get('type_jya', None)
    horses_query = Horse.query.filter(~Horse.name.startswith('*'))

    if order == 'name_asc':
        horses_query = horses_query.order_by(Horse.name.asc())
    elif order == 'name_desc':
        horses_query = horses_query.order_by(Horse.name.desc())
    elif order == 'birth_date_asc':
        horses_query = horses_query.order_by(Horse.date_of_birth.asc())
    elif order == 'birth_date_desc':
        horses_query = horses_query.order_by(Horse.date_of_birth.desc())
    elif order == 'entry_date_asc':
        horses_query = horses_query.order_by(Horse.date_of_entry.asc())
    elif order == 'entry_date_desc':
        horses_query = horses_query.order_by(Horse.date_of_entry.desc())

    horse_pagination = horses_query.paginate(page=page, per_page=per_page, error_out=False)
    horses = horse_pagination.items


    if q:
        horses = [horse for horse in horses if q.lower() in horse.name.lower()]
    
    if type_jya:
        horses = [horse for horse in horses if type_jya in horse.type_jya_assigned]

    
    return render_template('ecuestre/horse_list.html', horses=horses, order=order, q=q, pagination=horse_pagination, type_jya_assigned=type_jya, form=create_horse_Form())




@bp.route('/create', methods=['GET', 'POST'])
@permission_required('horse_new')
@inject_user_permissions
def create_horse_view():
    """
    Muestra el formulario para crear un nuevo caballo y maneja la creación del mismo al enviar el formulario.

    Esta función carga un formulario para ingresar los datos del caballo y los empleados relacionados. 
    Al enviar el formulario, se valida la información ingresada y, si es correcta, se registra un nuevo 
    caballo en la base de datos, junto con los empleados asignados y los tipos de jinetes y amazonas seleccionados.

    En caso de error durante el proceso de creación del caballo, la función recarga la plantilla con el 
    contexto necesario para mantener el estado del formulario y los datos.

    Returns:
        redirect
            - Si el formulario es válido y el caballo se crea correctamente, redirige a la lista de caballos.
        render_template: 
           - Si la validación falla o hay un error, renderiza 'ecuestre/create_horse.html' con las 
              variables `form` y `horses` en el contexto para recargar el formulario con los datos 
              existentes y mostrar información adicional en la vista.

    Raises:
        Exception: 
            - Si ocurre un error durante la creación del caballo, se muestra un mensaje de error mediante 
              `flash` y se recarga la plantilla para que el usuario pueda intentar nuevamente.
        
    """
    form = create_horse_Form()

    form.employees.choices = [(e.id, e.name) for e in Employee.query.all()]  # Cargar empleados previamente para que el usuario pueda ver y seleccionar los empleados disponibles al crear el caballo
    
    if form.validate_on_submit():
        try:
            type_jya_assigned=[] #Array de tipos de jinete/amazonas asignados
            if form.type_jya_hipoterapia.data:
                type_jya_assigned.append ("Hipoterapia")
            if form.type_jya_monta_terapeutica.data:
                type_jya_assigned.append ("Monta Terapéutica")
            if form.type_jya_dea.data:
                type_jya_assigned.append ("Deporte Ecuestre Adaptado")
            if form.type_jya_ar.data:
                type_jya_assigned.append ("Actividades Recreativas")
            if form.type_jya_equitacion.data:
                type_jya_assigned.append ("Equitación")
            
            
            new_horse = Horse(
                name=form.name.data,
                date_of_birth=form.date_of_birth.data,
                gender=form.gender.data,
                race=form.race.data,
                fur=form.fur.data,
                purchase_or_donation=form.purchase_or_donation.data,
                date_of_entry=form.date_of_entry.data,
                sede=form.sede.data,
                type_jya_assigned=type_jya_assigned,
            )


            for empleado_id in form.employees.data: # Asignar los empleados al caballo
                empleado = Employee.query.get(empleado_id)
                new_horse.employees.append(empleado)


            db.session.add(new_horse)
            db.session.commit()
            
            app.logger.info("Caballo creado exitosamente: %s", form.name.data)
            flash("Caballo creado exitosamente", "success")
            return redirect(url_for('horses.list_horses'))  # Redirigir a la lista de caballos
        except Exception as e:
            app.logger.error("Error al crear el caballo: %s", str(e))
            flash("Ocurrió un error al crear el caballo", "error")

 
    context = { #diccionario de datos que se pasa hacia las plantillas HTML 
        'form': form,  #Permitir que el formulario se renderice y mantenga su estado si ocurre un error.
        'horses': Horse.query.order_by(Horse.name).all() 
    }

    return render_template('ecuestre/horse_new.html', context=context)  # Renderizar el formulario


@bp.route('/editar/<int:horse_id>', methods=['GET', 'POST'])
@permission_required('horse_update')
@inject_user_permissions
def edit_horse(horse_id):

    """
        Edita la información de un caballo específico asociado a su ID.

    Esta función maneja la edición de los detalles de un caballo, permitiendo
    actualizar su nombre, fecha de nacimiento, género, raza, tipo de pelaje,
    método de adquisición, fecha de ingreso, sede, tipos de JYA asignados y
    empleados asociados. Los cambios se guardan en la base de datos.

    Args:
        horse_id (int): ID del caballo que se desea editar.

    Returns:
        redirect
            - Redirige a la lista de información del caballo actualizado si 
              el formulario se valida correctamente.
        render_template
            - Renderiza la plantilla 'ecuestre/edit_horse.html' con el formulario,
              la lista de empleados y el caballo si la solicitud es GET o si 
              el formulario no es válido.
    """

    employee_list = Employee.query.all()
    horse = Horse.query.get(horse_id)
    form = create_horse_Form(obj=horse)
    form.gender.choices = [('Macho', 'Macho'), ('Hembra', 'Hembra')]
    form.purchase_or_donation.choices = [('Compra', 'Compra'), ('Donación', 'Donación')]
    form.employees.choices = [(e.id, e.name) for e in employee_list]


    if form.validate_on_submit():
        horse.name = form.name.data
        horse.date_of_birth = form.date_of_birth.data
        horse.gender = form.gender.data
        horse.race = form.race.data
        horse.fur = form.fur.data
        horse.purchase_or_donation = form.purchase_or_donation.data
        horse.date_of_entry = form.date_of_entry.data
        horse.sede = form.sede.data
        
        type_jya = []
        if form.type_jya_hipoterapia.data:
            type_jya.append('Hipoterapia')
        if form.type_jya_monta_terapeutica.data:
            type_jya.append('Monta Terapéutica')
        if form.type_jya_dea.data:
            type_jya.append('Deporte Ecuestre Adaptado')
        if form.type_jya_ar.data:
            type_jya.append('Actividades Recreativas')
        if form.type_jya_equitacion.data:
            type_jya.append('Equitación')

        horse.type_jya_assigned = type_jya

        selected_employee_ids = form.employees.data
        selected_employees = Employee.query.filter(Employee.id.in_(selected_employee_ids)).all()
        horse.employees = selected_employees

        db.session.commit()
        flash('Horse updated successfully!', 'success')
        return redirect(url_for('horses.list_info_by_id', horse_id=horse.id))
    return render_template('ecuestre/horse_edit.html', form=form, employee_list=employee_list, horse=horse)


@bp.route('/eliminar/<int:horse_id>', methods=['POST'])

admin/src/web/templates/ecuestre/create_horse.html
{% extends "layout.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/auth.css') }}">
{% endblock %}
{% block title %}Agregar Nuevo Caballo{% endblock %}
{% block content %}
<div class="container">
    <h1 class="title is-size-2 has-text-centered has-text-black-bis mt-5">Agregar Nuevo Caballo</h1>

    <form method="POST" action="{{ url_for('horses.create_horse_view') }}">
        {{ context.form.hidden_tag() }}
        <div class="field">
            <label class="label">Nombre</label>
            <div class="control">
                {{ context.form.name(class="input") }}
            </div>
            {% for error in context.form.name.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Fecha de Nacimiento</label>
            <div class="control">
                {{ context.form.date_of_birth(class="input", type="date") }}
            </div>
            {% for error in context.form.date_of_birth.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Género</label>
            <div class="control">
                {{ context.form.gender(class="select") }}
            </div>
            {% for error in context.form.gender.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Raza</label>
            <div class="control">
                {{ context.form.race(class="input") }}
            </div>
            {% for error in context.form.race.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Pelaje</label>
            <div class="control">
                {{ context.form.fur(class="input") }}
            </div>
            {% for error in context.form.fur.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Compra o Donación</label>
            <div class="control">
                {{ context.form.purchase_or_donation(class="select") }}
            </div>
            {% for error in context.form.purchase_or_donation.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Fecha de Ingreso</label>
            <div class="control">
                {{ context.form.date_of_entry(class="input", type="date") }} 
            </div>
            {% for error in context.form.date_of_entry.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Sede</label>
            <div class="control">
                {{ context.form.sede(class="input") }}
            </div>
            {% for error in context.form.sede.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <label class="label">Tipo de Jinetes y Amazonas Asignados</label>
            <input type="checkbox" value="Hipoterapia" name="type_jya_hipoterapia">Hipoterapia
            <input type="checkbox" value="Monta Terapuetica" name="type_jya_monta_terapeutica">Monta Terapeutica
            <input type="checkbox" value="Deporte Ecuestre Adaptado" name="type_jya_dea">Deporte Ecuestre Adaptado
            <input type="checkbox" value="Actividades Recreativas" name="type_jya_ar">Actividades Recreativas
            <input type="checkbox" value="Equitacion" name="type_jya_equitacion">Equitacion
        </div>

        <div class="field">
            <label class="label">Asociar Entrenadores y Conductores</label>
            <div class="control">
                {% for id, name in context.form.employees.choices %}
            <label>
                <input type="checkbox" name="employees" value="{{ id }}"> {{ name }}
            </label><br>
                {% endfor %}
            </div>
            {% for error in context.form.employees.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="field">
            <div class="control">
                <button type="submit" class="button is-link">Crear Caballo</button>
            </div>
        </div>
    </form>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

admin/src/web/templates/ecuestre/horse_list.html
{% extends "layout.html" %}

{% block title %}Listado de caballos{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/payment_and_billing/list.css') }}">

{% endblock %}

{% block content %}

<div class="container">
    <div class="header-container">
        <h1 class="is-size-2-mobile is-size-2-tablet is-size-2-desktop">Lista de Caballos</h1>
        <a href="{{ url_for('horses.create_horse_view') }}" class="button is-white is-size-6">Agregar Caballo</a>
    </div>

    <div class="search-container">
        <form class="form-container" method="get" action="{{ url_for('horses.list_horses') }}">
            <div class="columns is-multiline">
                <div class="column is-narrow">
                    <input class="input" type="text" name="q" placeholder="Buscar por nombre" value="{{ request.args.get('q', '') }}">
                </div>
                <div class="column is-narrow">
                    <div class="select">
                        <select name="order" id="order" onchange="this.form.submit()">
                            <option value="name_asc" {% if order == 'name_asc' %}selected{% endif %}>Nombre: A-Z</option>
                            <option value="name_desc" {% if order == 'name_desc' %}selected{% endif %}>Nombre: Z-A</option>
                            <option value="birth_date_asc" {% if order == 'birth_date_asc' %}selected{% endif %}>Fecha de nacimiento: Menor-Mayor</option>
                            <option value="birth_date_desc" {% if order == 'birth_date_desc' %}selected{% endif %}>Fecha de nacimiento: Mayor-Menor</option>
                            <option value="entry_date_asc" {% if order == 'entry_date_asc' %}selected{% endif %}>Fecha de entrada: Menor-Mayor</option>
                            <option value="entry_date_desc" {% if order == 'entry_date_desc' %}selected{% endif %}>Fecha de entrada: Mayor-Menor</option>
                        </select>
                    </div>
                </div>
                <div class="column is-narrow">
                    <div class="select">
                        <select name="type_jya" id="type_jya" onchange="this.form.submit()">
                            <option value="">Tipo de jinetes y amazonas</option>
                            <option value="Hipoterapia" {% if type_jya_assigned == 'Hipoterapia' %}selected{% endif %}>Hipoterapia</option>
                            <option value="Monta Terapéutica" {% if type_jya_assigned == 'Monta Terapéutica' %}selected{% endif %}>Monta Terapéutica</option>
                            <option value="Deporte Ecuestre Adaptado" {% if type_jya_assigned == 'Deporte Ecuestre Adaptado' %}selected{% endif %}>Deporte Ecuestre Adaptado</option>
                            <option value="Actividades Recreativas" {% if type_jya_assigned == 'Actividades Recreativas' %}selected{% endif %}>Actividades Recreativas</option>
                            <option value="Equitación" {% if type_jya_assigned == 'Equitación' %}selected{% endif %}>Equitación</option>
                        </select>
                    </div>
                </div>
                <div class="column is-narrow">
                    <button type="submit" class="button search-button">Buscar</button>
                </div>
                <div class="column is-narrow">
                    <a class="button restore-button" href="{{ url_for('horses.list_horses', page=page) }}">Restablecer</a>
                </div>
            </div>
        </form>
    </div>

    <div class="table-container" style="overflow: hidden; overflow-x:auto">
        <table class="table is-striped horses">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Fecha de nacimiento</th>
                    <th>Genero</th>
                    <th>Raza</th>
                    <th>Pelaje</th>
                    <th>Compra/Donacion</th>
                    <th>Fecha de entrada</th>
                    <th>Sede</th>
                    <th>Tipo Jinetes/Amazonas asignados</th>
                    <th>Empleados</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% if horses %}
                    {% for horse in horses %}
                        <tr>
                            <td>
                                <a href="{{ url_for('horses.list_info_by_id', horse_id=horse.id) }}">
                                {{ horse.name }}
                                </a>
                            </td>
                            <td> {{ horse.date_of_birth.strftime('%d-%m-%Y') }} </td>
                            <td> {{horse.gender}} </td>
                            <td> {{horse.race}} </td>
                            <td> {{horse.fur}} </td>
                            <td> {{horse.purchase_or_donation}} </td>
                            <td> {{  horse.date_of_entry.strftime('%d-%m-%Y')  }} </td>
                            <td> {{horse.sede}} </td>
                            <td>
                            {% for type in horse.type_jya_assigned %}
                                {{ type }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                            </td>                   
                            <td>
                            {% for employee in horse.employees %}
                                {{ employee.name }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                            </td>
                            <td>
                                <a href="{{ url_for('horses.list_info_by_id', horse_id=horse.id) }}" class="button is-small is-white"><i class="fas fa-eye" title="Ver"></i></a>
                                <a href="{{ url_for('horses.edit_horse', horse_id=horse.id) }}" class="button is-small is-white"><i class="fas fa-edit" title="Editar"></i></a>
                                <form action="{{ url_for('horses.delete_horse', horse_id=horse.id) }}" 
                                method="POST" style="display: inline;">
                                    <button type="submit" class="button is-small is-white">
                                        <i class="fas fa-trash" title="Eliminar"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    
                    {% endfor %}
                {% else %}
                    <p style="text-align: center;">No hay caballos registrados en el sistema</p>
                {% endif %}
            </tbody>
        </table>
    </div>
    <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous" {% if not pagination.has_prev %}disabled{% else %}href="{{ url_for('horses.list_horses', page=pagination.prev_num,  order=order, q=q) }}"{% endif %}>Previous</a>
        <a class="pagination-next" {% if not pagination.has_next %}disabled{% else %}href="{{ url_for('horses.list_horses', page=pagination.next_num,  order=order, q=q) }}"{% endif %}>Next page</a>
    </nav>
</div>
<div id="deleteModal" class="modal">
    <div class="modal-content">
        <h3>¿Estás seguro de que deseas eliminar el caballo?</h3>
        <div class="modal-actions">
            <button id="cancelButton" class="button">Cancelar</button>
            <button id="confirmButton" class="button is-danger">Eliminar</button>
        </div>
    </div>
</div>

{% endblock %}

admin/src/web/templates/ecuestre/horses.html
{% extends "layout.html" %}

{% block title %}Listado de caballos{% endblock %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/payment_and_billing/list.css') }}">

{% endblock %}

{% block content %}

<div class="container">
    <div class="header-container">
        <h1 class="is-size-2-mobile is-size-2-tablet is-size-2-desktop">Lista de Caballos</h1>
        <a href="{{ url_for('horses.create_horse_view') }}" class="button is-white is-size-6">Agregar Caballo</a>
    </div>

    <div class="search-container">
        <form class="form-container" method="get" action="{{ url_for('horses.list_horses') }}">
            <div class="columns is-multiline">
                <div class="column is-narrow">
                    <input class="input" type="text" name="q" placeholder="Buscar por nombre" value="{{ request.args.get('q', '') }}">
                </div>
                <div class="column is-narrow">
                    <div class="select">
                        <select name="order" id="order" onchange="this.form.submit()">
                            <option value="name_asc" {% if order == 'name_asc' %}selected{% endif %}>Nombre: A-Z</option>
                            <option value="name_desc" {% if order == 'name_desc' %}selected{% endif %}>Nombre: Z-A</option>
                            <option value="birth_date_asc" {% if order == 'birth_date_asc' %}selected{% endif %}>Fecha de nacimiento: Menor-Mayor</option>
                            <option value="birth_date_desc" {% if order == 'birth_date_desc' %}selected{% endif %}>Fecha de nacimiento: Mayor-Menor</option>
                            <option value="entry_date_asc" {% if order == 'entry_date_asc' %}selected{% endif %}>Fecha de entrada: Menor-Mayor</option>
                            <option value="entry_date_desc" {% if order == 'entry_date_desc' %}selected{% endif %}>Fecha de entrada: Mayor-Menor</option>
                        </select>
                    </div>
                </div>
                <div class="column is-narrow">
                    <div class="select">
                        <select name="type_jya" id="type_jya" onchange="this.form.submit()">
                            <option value="">Tipo de jinetes y amazonas</option>
                            <option value="Hipoterapia" {% if type_jya_assigned == 'Hipoterapia' %}selected{% endif %}>Hipoterapia</option>
                            <option value="Monta Terapéutica" {% if type_jya_assigned == 'Monta Terapéutica' %}selected{% endif %}>Monta Terapéutica</option>
                            <option value="Deporte Ecuestre Adaptado" {% if type_jya_assigned == 'Deporte Ecuestre Adaptado' %}selected{% endif %}>Deporte Ecuestre Adaptado</option>
                            <option value="Actividades Recreativas" {% if type_jya_assigned == 'Actividades Recreativas' %}selected{% endif %}>Actividades Recreativas</option>
                            <option value="Equitación" {% if type_jya_assigned == 'Equitación' %}selected{% endif %}>Equitación</option>
                        </select>
                    </div>
                </div>
                <div class="column is-narrow">
                    <button type="submit" class="button search-button">Buscar</button>
                </div>
                <div class="column is-narrow">
                    <a class="button restore-button" href="{{ url_for('horses.list_horses', page=page) }}">Restablecer</a>
                </div>
            </div>
        </form>
    </div>

    <div class="table-container" style="overflow: hidden; overflow-x:auto">
        <table class="table is-striped horses">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Fecha de nacimiento</th>
                    <th>Genero</th>
                    <th>Raza</th>
                    <th>Pelaje</th>
                    <th>Compra/Donacion</th>
                    <th>Fecha de entrada</th>
                    <th>Sede</th>
                    <th>Tipo Jinetes/Amazonas asignados</th>
                    <th>Empleados</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% if horses %}
                    {% for horse in horses %}
                        <tr>
                            <td>
                                <a href="{{ url_for('horses.list_info_by_id', horse_id=horse.id) }}">
                                {{ horse.name }}
                                </a>
                            </td>
                            <td> {{ horse.date_of_birth.strftime('%d-%m-%Y') }} </td>
                            <td> {{horse.gender}} </td>
                            <td> {{horse.race}} </td>
                            <td> {{horse.fur}} </td>
                            <td> {{horse.purchase_or_donation}} </td>
                            <td> {{  horse.date_of_entry.strftime('%d-%m-%Y')  }} </td>
                            <td> {{horse.sede}} </td>
                            <td>
                            {% for type in horse.type_jya_assigned %}
                                {{ type }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                            </td>                   
                            <td>
                            {% for employee in horse.employees %}
                                {{ employee.name }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                            </td>
                            <td>
                                <a href="{{ url_for('horses.list_info_by_id', horse_id=horse.id) }}" class="button is-small is-white"><i class="fas fa-eye" title="Ver"></i></a>
                                <a href="{{ url_for('horses.edit_horse', horse_id=horse.id) }}" class="button is-small is-white"><i class="fas fa-edit" title="Editar"></i></a>
                                <form action="{{ url_for('horses.delete_horse', horse_id=horse.id) }}" 
                                method="POST" style="display: inline;">
                                    <button type="submit" class="button is-small is-white">
                                        <i class="fas fa-trash" title="Eliminar"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    
                    {% endfor %}
                {% else %}
                    <p style="text-align: center;">No hay caballos registrados en el sistema</p>
                {% endif %}
            </tbody>
        </table>
    </div>
    <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous" {% if not pagination.has_prev %}disabled{% else %}href="{{ url_for('horses.list_horses', page=pagination.prev_num,  order=order, q=q) }}"{% endif %}>Previous</a>
        <a class="pagination-next" {% if not pagination.has_next %}disabled{% else %}href="{{ url_for('horses.list_horses', page=pagination.next_num,  order=order, q=q) }}"{% endif %}>Next page</a>
    </nav>
</div>
<div id="deleteModal" class="modal">
    <div class="modal-content">
        <h3>¿Estás seguro de que deseas eliminar el caballo?</h3>
        <div class="modal-actions">
            <button id="cancelButton" class="button">Cancelar</button>
            <button id="confirmButton" class="button is-danger">Eliminar</button>
        </div>
    </div>
</div>

{% endblock %}