admin/src/web/controllers/team.py
from datetime import timedelta
from os import fstat
from flask import Blueprint, current_app as app, render_template, redirect, request, url_for, flash
from src.core.auth.models.user import User
from src.core.persons import create_employee_file, delete_employee_file_by_id, find_address_by_id, find_employee_by_id, find_employee_file_by_id, find_employee_file_by_title, get_emergency_contact_by_id, get_employee_user_by_id, get_files_by_employee_id, get_healthcare_plan_by_id, updated_employee_file
from src.core.auth.auth import inject_user_permissions, permission_required
from src.core.persons.models.person import Employee, Person
from src.core.persons.models.address import Address
from src.core.persons.models.healthcare_plan import HealthcarePlan
from src.core.persons.models.emergency_contact import EmergencyContact
from src.core.persons.forms import EmployeeFileForm, EmployeeForm
from src.core.database import db

bp = Blueprint('team', __name__, url_prefix='/empleados')


@bp.route('/')
@permission_required('team_index')
@inject_user_permissions
def list_team():
    """Redirige a la vista de listado de empleados, con los parámetros de orden, búsqueda, paginación y filtro aplicados.

    Returns:
        render_template: Renderiza la vista de listado de empleados con los parámetros de orden, búsqueda, paginación y filtro aplicados.
        employees: Lista de empleados que cumplen con los parámetros de orden, búsqueda, paginación y filtro aplicados.
        order: Parámetro de orden seleccionado.
        q: Parámetro de búsqueda seleccionado.
        pagination: Paginación de los empleados.
        job_position: Filtro de posición laboral seleccionado.
        form: Formulario de empleado.
    """
    order = request.args.get('order', 'last_name_asc')
    q = request.args.get('q', None)
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 25, type=int)
    job_position = request.args.get('job_position', None)

    # Ordeno según el parámetro seleccionado
    if order == 'last_name_asc':
        employees = Employee.query.order_by(Employee.last_name.asc())
    elif order == 'last_name_desc':
        employees = Employee.query.order_by(Employee.last_name.desc())
    elif order == 'name_asc':
        employees = Employee.query.order_by(Employee.name.asc())
    elif order == 'name_desc':
        employees = Employee.query.order_by(Employee.name.desc())
    elif order == 'date_asc':
        employees = Employee.query.order_by(Employee.start_date.asc())
    else:
        employees = Employee.query.order_by(Employee.start_date.desc())

    # Elimino del query aquellos empleados logicamente
    employees = employees.filter(Employee.email.notlike('*%'))

    # Aplico paginación al query
    employees_pagination = employees.paginate(
        page=page, per_page=per_page, error_out=False)

    # Me quedo con los objetos resultantes de la paginación
    employees = employees_pagination.items

    # Si se realizo una búsqueda, busco si "q" está presente en alguno de los campos
    if q:
        employees = [employee for employee in employees if q.lower() in employee.name.lower() or q.lower(
        ) in employee.last_name.lower() or q.lower() in employee.email.lower() or q in employee.DNI]

    # Si se aplico un filtro según la posición, me quedo solo con los que apliquen
    if job_position:
        employees = [
            employee for employee in employees if job_position == employee.job_position]

    return render_template('team/team_list.html', employees=employees, order=order, q=q, pagination=employees_pagination, job_position=job_position, form=EmployeeForm())


@bp.route('/crear', methods=['GET', 'POST'])
@permission_required('team_new')
@inject_user_permissions
def new_employee():
    """Redirige a la vista de creación de empleado, con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.

    Returns:
        render_template: Renderiza la vista de creación de empleado con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.
        professions: Lista de profesiones.
        form: Formulario de empleado.
        redirect: Redirige a la vista de listado de empleados si el formulario es válido.
    """
    form = EmployeeForm()
    form.address_id.choices = [(address.id, address.string())
                               for address in Address.query.all()]
    form.emergency_contact.choices = [(emergency_contact.id, emergency_contact.name,
                                       emergency_contact.phone_number) for emergency_contact in EmergencyContact.query.all()]
    form.user_id.choices = [(user.id, user.email) for user in User.query.all()]
    professions = ["Psicólogo", "Psicomotricista", "Médico", "Kinesiólogo", "Terapista Ocupacional",
                   "Psicopedagogo", "Docente", "Profesor", "Fonoaudiólogo", "Veterinario", "Otro"]

    if form.validate_on_submit():
        if form.address_id.data:
            address = Address.query.get(form.address_id.data)
        else:
            address = Address(
                street=form.new_address.street.data,
                number=form.new_address.number.data,
                department=form.new_address.department.data,
                locality=form.new_address.locality.data,
                province=form.new_address.province.data,
                phone_number=form.new_address.phone_number.data
            )
            db.session.add(address)
            db.session.commit()

        healthcare_plan = HealthcarePlan(
            social_security=form.healthcare_plan.social_security.data,
            affiliate_number=form.healthcare_plan.affiliate_number.data,
            has_guardianship=form.healthcare_plan.has_guardianship.data,
            observation=form.healthcare_plan.observation.data
        )
        db.session.add(healthcare_plan)
        db.session.commit()

        if form.emergency_contact.data:
            emergency_contact = EmergencyContact.query.get(
                form.emergency_contact.data)
        else:
            emergency_contact = EmergencyContact(
                name=form.new_emergency_contact.name.data,
                phone_number=form.new_emergency_contact.phone_number.data
            )
            db.session.add(emergency_contact)
            db.session.commit()

        employee = Employee(
            name=form.name.data,
            last_name=form.last_name.data,
            DNI=form.dni.data,
            phone_number=form.phone_number.data,
            address_id=address.id,
            profession=form.profession.data,
            job_position=form.job_position.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            emergency_contact_id_employee=emergency_contact.id,
            condition=form.condition.data,
            active=True,
            healthcare_plan_id_employee=healthcare_plan.id,
            email=form.email.data,
            birth_date=form.birth_date.data,
            user_id=form.user_id.data
        )
        db.session.add(employee)
        db.session.commit()
        flash('Employee created successfully!', 'success')
        return redirect(url_for('team.list_team'))

    return render_template('team/team_new.html', form=form, professions=professions)


@bp.route('/empleado/<int:id>')
@permission_required('team_show')
@inject_user_permissions
def show_employee(id):
    """Redirige a la vista de detalle de empleado, con los archivos asociados al empleado.

    Args:
        id (int): ID del empleado.

    Returns:
        render_template: Renderiza la vista de detalle de empleado con los archivos asociados al empleado.
        context: Contexto con los archivos asociados al empleado.
    """

    app.logger.info("Call to index function")

    employee = find_employee_by_id(id)

    # Quita el asterisco si el empleado fue eliminado logicamente
    if employee.email.startswith('*'):
        employee.email = employee.email[1:]

    employee_address = find_address_by_id(employee.address_id).string()
    employee_healthcare_plan = get_healthcare_plan_by_id(
        employee.healthcare_plan_id_employee)
    employee_emergency_contact = get_emergency_contact_by_id(
        employee.emergency_contact_id_employee)
    employee_user = get_employee_user_by_id(employee.user_id)
    files = get_files_by_employee_id(employee.id)
    employee_json = employee.to_dict(employee_address, employee_healthcare_plan,
                                     employee_emergency_contact, employee_user.email if employee_user else None)
    employee_json['active'] = 'Activo' if employee.active else 'Inactivo'

    files_json = []
    if files:
        for file in files:
            files_json.append(file.to_dict())

    if not employee_json['user']:
        employee_json['user'] = 'No asignado'

    context = {
        'files': files_json,
        'user': employee_json,
        'id': id,
    }

    app.logger.info("End of call to index function")

    return render_template('team/team_show.html', context=context)


@bp.route('/empleado/editar/<int:id>', methods=['GET', 'POST'])
@permission_required('team_update')
@inject_user_permissions
def edit_employee(id):
    """Redirige a la vista de edición de empleado, con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.

    Args:
        id (int): ID del empleado.

    Returns:
        render_template: Renderiza la vista de edición de empleado con el formulario de empleado y los campos de dirección, contacto de emergencia y obra social cargados.
        professions: Lista de profesiones.
        form: Formulario de empleado.
        redirect: Redirige a la vista de listado de empleados si el formulario es válido.
    """

    employee = Employee.query.get(id)
    employee.healthcare_plan = HealthcarePlan.query.get(
        employee.healthcare_plan_id_employee)

admin/src/web/templates/team/file_edit.html
{% extends "layout.html" %}

{% block title %}Editar Archivo{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/auth.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/horsemen_and_amazons/forms.css') }}">
{% endblock %}

{% block content %}

<form  method="POST" enctype="multipart/form-data" action="{{ url_for('team.edit_file', user_id=user_id, file_id=file.id) }}">
    
    {{ form.csrf_token }}
    <div class="div-titulo">
        <h1 class="label">Editar Archivo</h1>
        <hr class="linea-titulo">
    </div>

    <div id="contenedor">
        <label class="label">Archivo</label>
        <div class="control has-icons-left">
            <span class="icon is-small is-left">
                <i class="fas fa-file-upload"></i>
            </span>
            <input class="input" type="file" id="file_url" name="{{ form.file_url.name }}" placeholder="Selecciona el archivo" value="{{ form.file_url.value }}">
        </div>
        <hr>
    </div>

    <label class="label">Tipo de documento</label>
    <div class="control">
        <select class="file_type" id="document_type" name="{{ form.document_type.name }}" value="{{ file.document_type }}">
            <option>Selecciona un tipo de documento</option>
            <option {% if file.document_type == 'Título' %}selected{% endif %}>Título</option>
            <option {% if file.document_type == 'Copia DNI' %}selected{% endif %}>Copia DNI</option>
            <option {% if file.document_type == 'CV Actualizado' %}selected{% endif %}>CV Actualizado</option>
        </select>
    </div>
    <hr>

    <label class="label">Titulo</label>
    <div class="control has-icons-left">
        <span class="icon is-small is-left">
            <i class="fas fa-file-alt"></i>
        </span>
        <input class="input" type="text" id="title" required name="{{ form.title.name }}" placeholder="Ingrese el titulo del archivo" value="{{ file.title }}">
    </div>
    <hr>
    
    <div class="buttons">
        <button type="submit">Guardar cambios</button>
        <a href="{{ url_for('team.show_employee', id=user_id) }}"><button type="button" class="boton-cancelar">Cancelar</button></a>
    </div>
</form>

<script>    

document.addEventListener('DOMContentLoaded', () => {

    document.getElementById('fileForm').addEventListener('submit', function(event) {
        const fileInput = document.getElementById('fileInput');
        const file = fileInput.files[0];
        
        if (file) {
        const allowedExtensions = ['pdf', 'jpg', 'png']; // Extensiones permitidas
        const fileExtension = file.name.split('.').pop().toLowerCase();
        
        if (!allowedExtensions.includes(fileExtension)) {
            event.preventDefault();
            alert('Solo se permiten archivos con las extensiones: ' + allowedExtensions.join(', '));
        } else {
            alert('Archivo válido, se procederá con el envío.');
        }
        } else {
        event.preventDefault();
        alert('Por favor, selecciona un archivo.');
        }
    });
});
</script>
{% endblock %}

admin/src/web/templates/team/file_new.html
{% extends "layout.html" %}

{% block title %}Agregar Archivo{% endblock %}


{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/auth.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/horsemen_and_amazons/forms.css') }}">
{% endblock %}

{% block content %}

<form  id="fileForm" method="POST" enctype="multipart/form-data" action="{{ url_for('team.add_file', id=id) }}">
    
    {{ form.csrf_token }}
    <div class="div-titulo">
        <h1 class="label">Agregar Archivo</h1>
        <hr class="linea-titulo">
    </div>

    <label class="label">Tipo de documento</label>
    <div class="control">
        <select class="file_type" id="document_type" required name="{{ form.document_type.name }}" value="{{ form.document_type.value }}">
            <option>Selecciona un tipo de documento</option>
            <option>Título</option>
            <option>Copia DNI</option>
            <option>CV Actualizado</option>
        </select>
    </div>
    <hr>

    <label class="label">Titulo</label>
    <div class="control has-icons-left">
        <span class="icon is-small is-left">
            <i class="fas fa-file-alt"></i>
        </span>
        <input class="input" type="text" required id="title" name="{{ form.title.name }}" placeholder="Ingrese el titulo del archivo" value="{{ form.title.value }}">
    </div>
    <hr>
    
    <div id="contenedor">
        <label class="label">Archivo</label>
        <div class="control has-icons-left">
            <span class="icon is-small is-left">
                <i class="fas fa-file-upload"></i>
            </span>
            <input class="input" type="file" id="fileInput" required name="{{ form.file_url.name}}" value="{{ form.file_url.value }}">
        </div>  
        <hr>
    </div>

    <div class="buttons">
        <button type="submit">Agregar Archivo</button>
        <a href="{{ url_for('team.show_employee', id=id) }}"><button type="button" class="boton-cancelar">Cancelar</button></a>
    </div>

</form>

      <!-- Modal personalizado -->
    <div id="customAlert" class="modal">
        <div class="modal-content">
            <p id="alertMessage">Este es un mensaje de alerta personalizado.</p>
            <button id="closeAlert">Cerrar</button>
        </div>
    </div>
<script>    

        document.addEventListener('DOMContentLoaded', () => {

                function showCustomAlert(message) {
                    document.getElementById('alertMessage').innerText = message;
                    document.getElementById('customAlert').style.display = 'flex';
                }

                    // Función para cerrar el modal
                document.getElementById('closeAlert').addEventListener('click', function() {
                    document.getElementById('customAlert').style.display = 'none';
                });

                document.getElementById('fileForm').addEventListener('submit', function(event) {
                    const fileInput = document.getElementById('fileInput');
                    const file = fileInput.files[0];
                    
                    if (file) {
                        const allowedExtensions = ['pdf', 'jpeg', 'doc', 'xls']; // Extensiones permitidas
                        const fileExtension = file.name.split('.').pop().toLowerCase();
                    
                        if (!allowedExtensions.includes(fileExtension)) {
                            event.preventDefault();
                            showCustomAlert('Solo se permiten archivos con las extensiones: ' + allowedExtensions.join(', '));
                        } else {
                            // Archivo válido, puede continuar con el envío
                            showCustomAlert('Archivo válido, se procederá con el envío.');
                        }
                    } else {
                        event.preventDefault();
                        showCustomAlert('Por favor, selecciona un archivo.');
                    }
                });
        });
</script>
{% endblock %}

admin/src/web/templates/team/team_list.html
{% extends "layout.html" %}
{% block title %}Empleados{% endblock %}
{% block content %}

<div class="container">
    <div class="header-container">
        <h1 class="is-size-2-mobile is-size-2-tablet is-size-2-desktop">Lista de Empleados</h1>
        <a href="{{ url_for('team.new_employee') }}" class="button is-white is-size-6">Agregar empleado</a>
    </div>

    <div class="search-container">
        <form class="form-container" method="get" action="{{ url_for('team.list_team') }}">

            <div class="columns is-multiline">
                <div class="column is-narrow">
                    <input class="input" type="text" name="q" placeholder="Buscar" value="{{ request.args.get('q', '') }}">
                </div>
    
                <div class="column is-narrow">
                    <div class="select">
                        <select name="order" id="order" onchange="this.form.submit()">
                            <option value="name_asc" {% if order == 'name_asc' %}selected{% endif %}>Nombre: Orden Ascendente</option>
                            <option value="name_desc" {% if order == 'name_desc' %}selected{% endif %}>Nombre: Orden Descendente</option>
                            <option value="last_name_asc" {% if order == 'last_name_asc' %}selected{% endif %}>Apellido: Orden Ascendente</option>
                            <option value="last_name_desc" {% if order == 'last_name_desc' %}selected{% endif %}>Apellido: Orden Descendente</option>
                            <option value="date_asc" {% if order == 'date_asc' %}selected{% endif %}>Fecha de ingreso: Orden Ascendente</option>
                            <option value="date_desc" {% if order == 'date_desc' %}selected{% endif %}>Fecha de ingreso: Orden Descendente</option>
                        </select>
                    </div>
                </div>
    
                <div class="column is-narrow">
                    <div class="select">
                        <select name="job_position" id="job_position" onchange="this.form.submit()">
                            <option value="">Puesto laboral</option>
                            <option value="administrativo" {% if job_position == 'administrativo' %}selected{% endif %}>Administrativo/a</option>
                            <option value="terapeuta" {% if job_position == 'terapeuta' %}selected{% endif %}>Terapeuta</option>
                            <option value="conductor" {% if job_position == 'conductor' %}selected{% endif %}>Conductor</option>
                            <option value="auxiliar_de_pista" {% if job_position == 'auxiliar_de_pista' %}selected{% endif %}>Auxiliar de pista</option>
                            <option value="herrero" {% if job_position == 'herrero' %}selected{% endif %}>Herrero</option>
                            <option value="veterinario" {% if job_position == 'veterinario' %}selected{% endif %}>Veterinario</option>
                            <option value="entrenador_de_caballos" {% if job_position == 'entrenador_de_caballos' %}selected{% endif %}>Entrenador de Caballos</option>
                            <option value="domador" {% if job_position == 'domador' %}selected{% endif %}>Domador</option>
                            <option value="profesor_de_equitacion" {% if job_position == 'profesor_de_equitacion' %}selected{% endif %}>Profesor de Equitación</option>
                            <option value="docente_de_capacitacion" {% if job_position == 'docente_de_capacitacion' %}selected{% endif %}>Docente de Capacitación</option>
                            <option value="auxiliar_de_mantenimiento" {% if job_position == 'auxiliar_de_mantenimiento' %}selected{% endif %}>Auxiliar de mantenimiento</option>
                            <option value="otro" {% if job_position == 'otro' %}selected{% endif %}>Otro</option>
                        </select>
                    </div>
                </div>
    
                <div class="column is-narrow">
                    <button type="submit" class="button search-button">Buscar</button>
                </div>
                
                <div class="column is-narrow">
                    <a class="button restore-button" href="{{ url_for('team.list_team', page=page)}}">Restablecer</a>
                </div>
            </div>
        </form>
    </div>

    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>DNI</th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Puesto laboral</th>
                    <th>Actividad</th>
                    <th>Fecha de inicio</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% if employees %}
                    {% for employee in employees %}
                    <tr>
                        <td><a href="{{ url_for('team.show_employee', id=employee.id) }}">{{ employee.DNI }}</a></td>
                        <td>{{ employee.last_name }}</td>
                        <td>{{ employee.name }}</td>
                        <td>{{ employee.email }}</td>
                        <td>{{ employee.job_position }}</td>
                        {% if employee.active %}
                            <td>Activo</td>
                        {% else %}
                            <td>Inactivo</td>
                        {% endif %}
                        <td>{{ employee.start_date.strftime('%Y/%m/%d') }}</td>
                        <td>
                            <a href="{{ url_for('team.show_employee', id=employee.id) }}" class="button is-small is-white"><i class="fas fa-eye" title="Ver"></i></a>
                            <a href="{{ url_for('team.edit_employee', id=employee.id) }}" class="button is-small is-white"><i class="fas fa-edit" title="Editar"></i></a>
                            <a class="button is-small is-white delete-button" data-employee-id="{{ employee.id }}" data-employee-dni="{{ employee.DNI }}"><i class="fas fa-trash" title="Eliminar"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5">No hay empleados</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous" {% if not pagination.has_prev %}disabled{% else %}href="{{ url_for('team.list_team', page=pagination.prev_num,  order=order, q=q) }}"{% endif %}>Previous</a>
        <a class="pagination-next" {% if not pagination.has_next %}disabled{% else %}href="{{ url_for('team.list_team', page=pagination.next_num,  order=order, q=q) }}"{% endif %}>Next page</a>
    </nav>
</div>

<div id="deleteModal" class="modal">
    <div class="modal-content">
        <h3>¿Estás seguro de que deseas eliminar el empleado de DNI: <span id="employeeDNIToDelete"></span>?</h3>
        <div class="modal-actions">
            <button id="cancelButton" class="button">Cancelar</button>
            <button id="confirmButton" class="button is-danger">Eliminar</button>
        </div>
    </div>
</div>

<style>
    select {
        width: auto !important;
    }

    .container {
        width: 70%;
    }

    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .search-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 10px;
    }

    .table-container {
        width: 100%;
        margin: 0 auto;
    }
    
    .table {
        width: 100%;
        margin: 0 auto;
        border-collapse: collapse;
    }
    
    .table th, .table td {
        padding: 8px;
    }
    
    .table th {
        text-align: left;
    }

    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 400px;
    }

    .modal-actions {
        display: flex;
        justify-content: space-between;
    }

</style>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const deleteButtons = document.querySelectorAll('.delete-button');
        const deleteModal = document.getElementById('deleteModal');
        const cancelButton = document.getElementById('cancelButton');
        const confirmButton = document.getElementById('confirmButton');
        const employeeDNIToDeleteSpan = document.getElementById('employeeDNIToDelete');
        let employeeIDToDelete = null;

        deleteButtons.forEach(button => {
            button.addEventListener('click', function () {
                employeeIDToDelete = this.dataset.employeeId;
                employeeDNIToDelete = this.dataset.employeeDni;
                employeeDNIToDeleteSpan.textContent = employeeDNIToDelete;
                deleteModal.style.display = 'block';
            });
        });

        cancelButton.addEventListener('click', function () {
            deleteModal.style.display = 'none';
            employeeIDToDelete = null;
        });

        confirmButton.addEventListener('click', function () {
            if (employeeIDToDelete) {
                fetch(`/empleados/eliminar/${employeeIDToDelete}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ form.csrf_token._value() }}'
                    }
                }).then(response => {
                    if (response.ok) {
                        window.location.reload();
                    } else {
                        alert('Error al eliminar el empleado');
                    }
                });
            }
        });

        window.onclick = function (event) {
            if (event.target == deleteModal) {
                deleteModal.style.display = 'none';
            }
        }
    });
</script>
{% endblock %}